version: '3'

services:
  map:
    hostname: 'map-service'
    build: . # Build the image from the current directory (adjust if needed)

    working_dir: /app

    environment:
      - NODE_ENV=production
      - VITE_PORT=5050

    env_file:
      - .env

    ports:
      - '5050:5050'

    restart: unless-stopped
