version: '3'

services:
  svelte-app:
    build: . # Build the image from the current directory (adjust if needed)

    working_dir: /app

    environment:
      - NODE_ENV=production
      - VITE_PORT=5174
    
    env_file:
      - .env

    ports:
      - '5050:5174'

    restart: unless-stopped
